name: Flutter Windows and macOS Build
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          touch .env
      - name: Build for Windows
        run: flutter build windows
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/windows/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          touch .env
      - name: Build for macOS
        run: flutter build macos
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: build/macos/
